# Generated by Django 5.1.1 on 2024-09-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('registro', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
            },
        ),
        migrations.CreateModel(
            name='Engenheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('registro', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Engenheiro',
                'verbose_name_plural': 'Engenheiros',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_venda', models.CharField(max_length=3)),
                ('preco_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_aluguel', models.CharField(max_length=3)),
                ('categoria', models.CharField(max_length=100)),
                ('comodos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizacaoGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=40)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('quadra', models.CharField(max_length=10)),
                ('lote', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OficioNotarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notarialCountry', models.CharField(max_length=100)),
                ('notarialStates', models.CharField(max_length=100)),
                ('notarialMunicipality', models.CharField(max_length=100)),
                ('notarialNeighborhood', models.CharField(max_length=100)),
                ('notarialStreet', models.CharField(max_length=100)),
                ('notarialBlock', models.CharField(max_length=100)),
                ('notarialLot', models.CharField(max_length=100)),
                ('notarialRegistration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoArquitetonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_quadrados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art_numero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeZoneamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneamento', models.CharField(choices=[('ZR1', 'Zona Residencial (ZR1)'), ('ZR2', 'Zona Residencial (ZR2)'), ('ZR3', 'Zona Residencial (ZR3)'), ('ZRE', 'Zona Residencial Especial (ZRE)'), ('ZC1', 'Zona Comercial (ZC1)'), ('ZC2', 'Zona Comercial (ZC2)'), ('ZC3', 'Zona Comercial (ZC3)'), ('ZCE', 'Zona Comercial Especial (ZCE)'), ('ZI1', 'Zona Industrial (ZI1)'), ('ZI2', 'Zona Industrial (ZI2)'), ('ZI3', 'Zona Industrial (ZI3)'), ('ZIE', 'Zona Industrial Especial (ZIE)'), ('ZPA', 'Zona de Preservação Ambiental (ZPA)'), ('ZPR', 'Zona de Proteção Ambiental (ZPR)'), ('ZRA', 'Zona de Recuperação Ambiental (ZRA)'), ('ZR', 'Zona Rural (ZR)'), ('ZA', 'Zona Agrícola (ZA)')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressCountry', models.CharField(max_length=100)),
                ('addressStates', models.CharField(max_length=40)),
                ('municipality', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=10)),
                ('iptuRegistration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_utm', models.IntegerField()),
                ('meridiano_central', models.IntegerField()),
                ('latitude_utm', models.FloatField()),
                ('longitude_utm', models.FloatField()),
                ('sistema_geodesico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('registro', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Topógrafo',
                'verbose_name_plural': 'Topógrafos',
            },
        ),
        migrations.CreateModel(
            name='EscrituraImobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
                ('localizacao_geografica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escritura_imobiliaria', to='dashboard.localizacaogeografica')),
            ],
        ),
    ]
